input {
  beats {
    port => 5044
  }
}

filter {
  if [event_type] {
    mutate {
      add_field => { "log_source" => "suricata" }
    }

    if [event_type] == "alert" {
      mutate {
        add_field => { "alert_detected" => "true" }
      }
    }

    if [src_ip] {
      geoip {
        source => "src_ip"
        target => "src_geoip"
      }
    }

    if [dest_ip] {
      geoip {
        source => "dest_ip"
        target => "dest_geoip"
      }
    }

    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }
  }
}

output {
  if [log_source] == "suricata" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "suricata-%{+YYYY.MM.dd}"
    }
  }

  stdout {
    codec => rubydebug
  }
}
